### ISSUE TITLE
use .service on ubuntu

### ISSUE THREAD

**Issue by zabbal** [oVirt/ovirt-guest-agent#4]
The .deb packages should use .service and systemd instead of deprecated upstart.

**Comment by vinzenz** [comment]
Even though I know you're right, those debian files were for a previous version and the internally managed debian files aren't really updated anymore as they do not give a good way of handling multiple targets. differences between the support ubuntu *, debian * etc are far to big to keep that internally managed.

**Comment by vinzenz** [comment]
Just FYI the external management of those files is at build.opensuse.org at this point
